# Generated by Django 4.0.1 on 2022-02-23 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_code', models.IntegerField(primary_key=True, serialize=False)),
                ('course_title', models.CharField(max_length=50)),
                ('hours', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('title', models.CharField(max_length=50)),
                ('degree_code', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_code', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('faculty', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('DOB', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Takes',
            fields=[
                ('course_reg_number', models.IntegerField(primary_key=True, serialize=False)),
                ('year', models.DateField()),
                ('course_code_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_tables.course')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_tables.student')),
            ],
        ),
        migrations.CreateModel(
            name='Requires',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course_code_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_tables.course')),
                ('degree_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_tables.degree')),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.DateField()),
                ('degree_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_tables.degree')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_tables.student')),
            ],
        ),
        migrations.AddField(
            model_name='degree',
            name='department_code_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_tables.department'),
        ),
    ]
